NovaStream/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    # set the router for main_app
    path('',include('main_app.urls')),
    # set the pre-set routes for login and logout
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
# ////////// IMPORTS //////////////////////
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home_index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('signup', views.signup, name='signup'),
    
    path('posts/', views.PostList.as_view(), name='post_list'),
    path('posts/create/', views.PostCreate.as_view(), name='post_create'),
    path('posts/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('posts/<int:pk>/update/', views.PostUpdate.as_view(), name='post_update'),
    path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),

    path('posts/<int:user_id>/add_photo/', views.add_photo, name='add_photo'),
    path('posts/<int:post_id>/add_image/', views.add_image, name='add_image'),
    path('posts/<int:photo_id>/remove_photo/', views.remove_photo, name='remove_photo'),
    
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True)
    imageUrl = models.CharField(max_length=200, blank=True)
    videoUrl = models.CharField(max_length=100, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    datePublished = models.DateTimeField(auto_now_add=True)
    
class Photo(models.Model):
    url = models.CharField(max_length=200, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.url

class Image(models.Model):
    url = models.CharField(max_length=200, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.url

main_app/forms.py
# //////////////////// IMPORTS //////////////////////
from django.forms import ModelForm
# from .models import

# //////////////////////////////////////////////////////

main_app/views.py
#  ////////////////// IMPORTS //////////////////////////////////////
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Post, Photo, Image
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import boto3
import uuid
from datetime import date
from django.utils import timezone

# Make sure to add your bucket name below
S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com'
BUCKET = 'novastream-posts'

# Create your views here.
def signup(request):
    error_msg = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_msg = 'Invalid Credentials - Try again.'
    form = UserCreationForm()
    context = {'form': form, 'error_msg': error_msg}
    return render(request, 'registration/signup.html', context)


def home_index(request):
    posts = Post.objects.all().order_by('-datePublished')[:5]
    return render(request, 'home.html',{'posts':posts})

def about(request):
    return render(request, 'about.html')

@login_required  
def profile(request):
    posts = Post.objects.filter(author=request.user)
    return render(request, 'profile.html', {'posts': posts})

@login_required
def add_image(request, post_id):
    img_file = request.FILES.get('img-file', None)
    if img_file:
        s3 = boto3.client('s3')
        file_extension = img_file.name[img_file.name.rfind('.') :]
        key = uuid.uuid4().hex[:6] + file_extension

        try:
            s3.upload_fileobj(img_file, BUCKET, key)
            url = f"{S3_BASE_URL}/{BUCKET}/{key}"
            post = Post.objects.get(pk=post_id)
            post.imageUrl = url
            post.save()
        except:
            print('add_image() Failed. Error while uploading file to S3')
    return redirect('post_detail', post_id)

@login_required
def add_photo(request, user_id):
    img_file = request.FILES.get('img-file', None)
    if img_file:
        s3 = boto3.client('s3')
        file_extension = img_file.name[img_file.name.rfind('.') :]
        key = uuid.uuid4().hex[:6] + file_extension

        try:
            s3.upload_fileobj(img_file, BUCKET, key)
            url = f"{S3_BASE_URL}/{BUCKET}/{key}"
            photo = Photo(url=url, user_id=user_id)
            photo.save()
        except:
            print('add_photo() Failed. Error while uploading file to S3')
    return redirect('profile')


@login_required
def remove_photo(request, photo_id):
    user = request.user
    photo = Photo.objects.get(pk=photo_id)
    photo.delete()
    return redirect('/profile/')

class PostList(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'post_list'

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'imageUrl', 'videoUrl']
    success_url = '/posts/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.now()
        context['date_now'] = date.today().strftime('dd/mm/YYYY')
        return context

class PostDetail(LoginRequiredMixin, DetailView):
    model = Post

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'imageUrl', 'videoUrl']
    success_url = '/posts/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.now()
        context['date_now'] = date.today().strftime('dd/mm/YYYY')
        return context

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/posts/'

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>NovaStream</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <a href="/" class="left brand-logo">
                        <img id="logo" src="{% static 'images/novastream.png'%}" alt="NovaStream Logo"> </ul>
                <ul class="right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'post_list' %}">Posts</a></li>
                    <li><a href="{% url 'profile' %}">Profile</a></li>
                    <li><a href="{% url 'logout' %}">Sign Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Sign In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1 id="home-title"><b>Welcome to</b><img id="logo-large" src="../static/images/novastream.png"></h1>
<div class="swipeView">
    {% for post in posts %}
    <section class="green-4">
        <a id="btn" href="{% url 'post_detail' post.id %}">
            <div id="post-title-photo">
                <div class="row">
                    <div class="col s4 post-title-photo" style="background-image: url('{{post.imageUrl}}');">
                    </div>
                    <div id=" image_title " class="col s8 ">
                        <h3>{{post.title}}</h3>
                    </div>
                </div>
            </div>
        </a>
    </section>
    {% endfor %}
</div>

<script>
    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("green-4");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) {
            myIndex = 1
        }
        x[myIndex - 1].style.display = "block";
        x[myIndex - 1].style.transition = "3s";
        setTimeout(carousel, 5000);
    }
</script>
{% endblock %}

main_app/templates/main_app/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Confirm Delete</h1>
<form action="" method="POST">
    {% csrf_token %}
<h4>Are you sure you want to delete this post?</h4>
<input type="submit" class="btn red" value="Yes - Delete">
</form>
{% endblock %}

main_app/templates/main_app/post_detail.html
{% extends 'base.html' %} {% block content %}
<div class="post-body">
    {% if object%}
    <h1>{{object.title}}</h1>
    <i>{{object.datePublished|date }}</i>
    <h6><b>{{post.author}}</b></h6>
    <div class="post-title-photo" style="background-image: url({{post.imageUrl}});"></div>
    <p>{{object.content|linebreaks}}</p>
</div>
{% if user == object.author %}
<a href="{% url 'post_delete' object.id %}"><button class="btn red" style="float:right;">Delete Post</button></a>
<a href="{% url 'post_update' object.id %}"><button class="btn blue" style="float:right;">Edit Post</button></a> {% endif %} {% endif %} {% endblock %}

main_app/templates/main_app/post_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit<span class="blue-text">{{object.name}}</span></h1>
<form action="" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col s6">
            <input id="id_title" type="text" name="title" placeholder="Title" value="{{object.title}}">
        </div>
        <div class="col s6">
            <input type="text" name="datePublished" value="{{time_now|date}} - {{ time_now|time }}" readonly>
        </div>
    </div>
    <div class="row">
        <div class="col s6">
            <p><b>Image URL:</b></p><input id="id_imageUrl" type="text" name="imageUrl" placeholder="Image Url" value="{{object.imageUrl}}">
        </div>
        <div class="col s6">
            <p><b>Video URL:</b></p><input id="id_videoUrl" type="text" name="videoUrl" placeholder="Video Url" value="{{object.videoUrl}}">
        </div>
    </div>
    <textArea id="id_content" name="content" placeholder="Content">
    {{object.content}}
    </textarea> {% if user == object.author%}
    <input type="submit" class="btn green" value="Submit">
    <a href="{% url 'post_detail' object.id %}">
        <input type="button" class="btn grey" value="Cancel"></a>
    {% endif %}
</form>
{% else %}
<h1>Add Post</h1>
<form action="" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col s6">
            <input id="id_title" type="text" name="title" placeholder="Title">
        </div>
        <div class="col s6">
            <input type="hidden" name="datePublished" value="{{time_now|date}} - {{ time_now|time }}">
            <p style="float: right;">{{time_now|date}} - {{time_now|time}}</p>
        </div>
    </div>
    <div class="row">
        <div class="col s6">
            <input id="id_imageUrl" type="text" name="imageUrl" placeholder="Image Url" value="{{object.imageUrl}}">
        </div>
        <div class="col s6">
            <input id="id_videoUrl" type="text" name="videoUrl" placeholder="Video Url" value="{{object.videoUrl}}">
        </div>
    </div>
    <div class="row">
        <textArea id="id_content" name="content" placeholder="Content"></textarea>
    </div>
    <input type="submit" class="btn green" value="Submit">
</form>
{% endif %} {% endblock %}

main_app/templates/main_app/post_list.html
{% extends 'base.html' %} {% block content %}
<h1>Posts</h1>
<a href=" {% url 'post_create' %} "><button class="btn " style="float:right; margin-top: -50px; ">Add Post</button></a> {% for post in post_list %}
<div class=card>
    <a href="{% url 'post_detail' post.id %} ">
        <div class=card-content>
            <div class="row ">
                <div class="col s3 ">
                    <div id="post_image" style="background-image: url({{post.imageUrl}});"></div>
                </div>
                <div class="col s9 ">
                    <h5>{{post.title}}</h5>
                    <h8>{{post.author}}</h8>
                    <p><i>{{post.datePublished|date}}</i></p>
                </div>
            </div>
        </div>
    </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %} {% block content %}
<h1>Profile</h1>
<div class="row">
    <div class="col s3">
        <div class="round">
            {% if user.photo_set.first %}
            <a href="{% url 'remove_photo' user.photo_set.first.id %}">
                <div class="profile-photo" style="background-image: url({{user.photo_set.first}});"></div>
            </a>{% else %}
            <form action="{% url 'add_photo' user.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="img-file">
                <br><br>
                <input type="submit" class="btn green" value="Add Image">
            </form>
            {% endif %}
        </div>
    </div>
    <div class="col s9">
        <div class="small-card">
            <div class="card-content">
                <h3 class="capitalized">{{user}}</h3>
            </div>
        </div>
    </div>
</div>
<a href="{% url 'post_create' %}"><button class="btn" style="float:right; margin-top: 20px;">Add Post</button></a>
<h3>My Posts</h3>
{% for post in posts %}
<div class="card small-card">
    <a href="{% url 'post_detail' post.id %}">
        <div class="card-content">
            <div class="col s12">
                <h5>{{post.title}}</h5>
                <p><i>{{post.datePublished|date}}</i></p>
            </div>
        </div>
    </a>
</div>
{% endfor %} {% endblock %}